title: UK
description: My Personal Blog
author: kiuk jung
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/falhed7418
about: developer

baseurl: "https://falhed7418.github.io/"
url: "https://falhed7418.github.io/"

allowsearch: true

disqus_shortname:
google_analytics:

share:
  twitter_username: \#
  fb_appid:


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
